name: hello
on: 
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: pages

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Hello world
      env:
        HELLO: ${{ vars.HELLO }}
        HELLO_SECRET: ${{ secrets.HELLO_SECRET }}
      run: echo Hello, world! "$HELLO" "$HELLO_SECRET"

    - name: Setup Go Runtime
      uses: actions/setup-go@v5
      id: setup-go
      with:
        go-version: 1.17

    - name: check cache hits
      run: echo "Cache hit ${{ steps.setup-go.outputs.cache-hit }}"