name: hello
on: 
  schedule:
    - cron: '*/15 * * * *'
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world
      run: echo Hello, world!
      
    - name: Super-linter
      uses: super-linter/super-linter@v7.2.1 # x-release-please-version
      env:
        # To report GitHub Actions status checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}