name: hello
on: 
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Hello world
      env:
        HELLO: ${{ vars.HELLO }}
        HELLO_SECRET: ${{ secrets.HELLO_SECRET }}
      run: echo Hello, world! "$HELLO" "$HELLO_SECRET"