name: parallel
on: 
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: first-steps-1
        run : sleep 5 && echo "first job-1"
      - name: first-steps-2
        run : sleep 5 && echo "first job-2"
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: second-steps
        run : sleep 10 && echo "second job"
  third:
    runs-on: ubuntu-latest
    needs: second
    steps:
      - name: third-steps
        run : sleep 20 && echo "third job"