name: parallel
on: 
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: pages

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run : sleep 5 && echo "first job"
  second:
    runs-on: ubuntu-latest
    steps:
      - run : sleep 10 && echo "second job"
  third:
    runs-on: ubuntu-latest
    steps:
      - run : sleep 20 && echo "third job"